---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  become: True
  unarchive:
    src: files/artifact.tar.gz
    # src: artifact.tar.gz
    # dest: ~/backend-app
    dest: /home/ubuntu

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: Start app
  become: True
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm --start

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu